"""add cascade behaviour

Revision ID: 8e086c0c54ab
Revises: 260bc4def97b
Create Date: 2025-05-09 16:53:08.817498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e086c0c54ab"
down_revision: Union[str, None] = "260bc4def97b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_followers_following_id_users", "followers", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_followers_follower_id_users", "followers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_followers_following_id_users"),
        "followers",
        "users",
        ["following_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_followers_follower_id_users"),
        "followers",
        "users",
        ["follower_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_tweets_attachments_tweet_id_tweets",
        "tweets_attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_tweets_attachments_attachment_id_attachments",
        "tweets_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_tweets_attachments_tweet_id_tweets"),
        "tweets_attachments",
        "tweets",
        ["tweet_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_tweets_attachments_attachment_id_attachments"),
        "tweets_attachments",
        "attachments",
        ["attachment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_tweets_likes_tweet_id_tweets", "tweets_likes", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_tweets_likes_user_id_users", "tweets_likes", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tweets_likes_tweet_id_tweets"),
        "tweets_likes",
        "tweets",
        ["tweet_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_tweets_likes_user_id_users"),
        "tweets_likes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_users_keys_user_id_users", "users_keys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_users_keys_user_id_users"),
        "users_keys",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_keys_user_id_users"), "users_keys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_users_keys_user_id_users",
        "users_keys",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_tweets_likes_user_id_users"),
        "tweets_likes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_tweets_likes_tweet_id_tweets"),
        "tweets_likes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_tweets_likes_user_id_users",
        "tweets_likes",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_tweets_likes_tweet_id_tweets",
        "tweets_likes",
        "tweets",
        ["tweet_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_tweets_attachments_attachment_id_attachments"),
        "tweets_attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_tweets_attachments_tweet_id_tweets"),
        "tweets_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_tweets_attachments_attachment_id_attachments",
        "tweets_attachments",
        "attachments",
        ["attachment_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_tweets_attachments_tweet_id_tweets",
        "tweets_attachments",
        "tweets",
        ["tweet_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_followers_follower_id_users"), "followers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_followers_following_id_users"),
        "followers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_followers_follower_id_users",
        "followers",
        "users",
        ["follower_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_followers_following_id_users",
        "followers",
        "users",
        ["following_id"],
        ["id"],
    )
    # ### end Alembic commands ###
