"""add tweet, like, attachment models

Revision ID: 260bc4def97b
Revises: 295358d577f0
Create Date: 2025-05-07 22:53:09.543688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "260bc4def97b"
down_revision: Union[str, None] = "295358d577f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_tweets_author_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tweets")),
    )
    op.create_table(
        "tweets_attachments",
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_tweets_attachments_attachment_id_attachments"),
        ),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
            name=op.f("fk_tweets_attachments_tweet_id_tweets"),
        ),
        sa.PrimaryKeyConstraint(
            "tweet_id", "attachment_id", name=op.f("pk_tweets_attachments")
        ),
    )
    op.create_table(
        "tweets_likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
            name=op.f("fk_tweets_likes_tweet_id_tweets"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tweets_likes_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("user_id", "tweet_id", name=op.f("pk_tweets_likes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets_likes")
    op.drop_table("tweets_attachments")
    op.drop_table("tweets")
    op.drop_table("attachments")
    # ### end Alembic commands ###
