"""set user_id unique

Revision ID: 295358d577f0
Revises: bc9cabba45f5
Create Date: 2025-05-05 15:17:03.463728

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "295358d577f0"
down_revision: Union[str, None] = "bc9cabba45f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_keys_user_id"), "users_keys", ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_keys_user_id"), "users_keys", type_="unique")
    # ### end Alembic commands ###
