"""create user-key asossiation table

Revision ID: bc9cabba45f5
Revises: 0f138460004d
Create Date: 2025-05-05 13:49:30.892175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc9cabba45f5"
down_revision: Union[str, None] = "0f138460004d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_keys",
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_users_keys_user_id_users")
        ),
        sa.PrimaryKeyConstraint("api_key", name=op.f("pk_users_keys")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_keys")
    # ### end Alembic commands ###
